base_url = "https://port19.xyz"
title = "Port19s Webpage"
generate_feeds = true
feed_filenames = ["rss.xml"]

[markdown]
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "ayu-dark"
render_emoji = true
