base_url = "https://port19.xyz"
title = "Port19's Webpage"
generate_feed = true
feed_filename = "rss.xml"

[markdown]
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "ayu-dark"
render_emoji = true
