name: Zola on GitHub Pages

on:
 push:
  branches:
   - master

jobs:
  dead-links:
    name: Dead Link Checker
    runs-on: ubuntu-latest
    steps:
    - name: Run DeadFinder
      uses: hahwul/deadfinder@1.3.3
      id: broken-link
      with:
        command: sitemap
        target: "https://port19.xyz/sitemap.xml"
  trailing-ws:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ocular-d/trailing-spaces@0.0.2
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v3
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout gh-pages
      uses: actions/checkout@v4
      with:
        ref: gh-pages
    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete
        remote_path: /root/port19.xyz/
        remote_host: ansible.how
        remote_user: root
        remote_key: ${{ secrets.SSH_KEY }}
