name: Zola on GitHub Pages

on:
 push:
  branches:
   - master

jobs:
  dead-links:
    name: Run Deadsniper
    runs-on: ubuntu-latest
    steps:
    - name: Run Deadsniper
      run: |
        wget "https://github.com/port19x/deadsniper/releases/download/v1.1/deadsniper" && chmod +x ./deadsniper && ./deadsniper https://port19.xyz/sitemap.xml
  trailing-ws:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ocular-d/trailing-spaces@0.0.2
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v3
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
