name: Zola on Nginx

on:
  deployment

jobs:
  rsync:
    runs-on: ubuntu/latest
    steps:
    - name: Checkout gh-pages
      uses: actions/checkout@v4
      with:
        ref: gh-pages
    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete
        remote_path: /root/port19.xyz/
        remote_host: ansible.how
        remote_user: root
        remote_key: ${{ secrets.SSH_KEY }}
